services:
  - type: web
    name: teger-guardrails-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOW_ORIGINS
        value: "*"
      - key: INTERSWITCH_MODE
        value: mock
  - type: static
    name: teger-guardrails-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://teger-guardrails-backend.onrender.com
